version: "3.8"
services: 
    zookeeper1:
        image: zookeeper
        restart: always
        hostname: zookeeper1
        ports:
          - 2181:2181
        environment:
          ZOO_MY_ID: 1
          ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    
    zookeeper2:
        image: zookeeper
        restart: always
        hostname: zookeeper2
        ports:
          - 2182:2181
        environment:
          ZOO_MY_ID: 2
          ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    
    zookeeper3:
        image: zookeeper
        restart: always
        hostname: zookeeper3
        ports:
          - 2183:2181
        environment:
          ZOO_MY_ID: 3
          ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    kafka1:
        container_name: kafka1
        image: confluentinc/cp-kafka
        restart: always
        ports:
            - 9092:9092
        environment: 
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181, zookeeper2:2181, zookeeper3:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9092
        depends_on:
            - zookeeper1
            - zookeeper2
            - zookeeper3
    kafka2:
        container_name: kafka2
        image: confluentinc/cp-kafka
        restart: always
        ports:
            - 9093:9093
        environment: 
            KAFKA_BROKER_ID: 2
            KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181, zookeeper2:2182, zookeeper3:2183
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9093
        depends_on:
            - zookeeper1
            - zookeeper2
            - zookeeper3
    kafka3:
        container_name: kafka3
        image: confluentinc/cp-kafka
        restart: always
        ports:
            - 9094:9094
        environment: 
            KAFKA_BROKER_ID: 3
            KAFKA_ZOOKEEPER_CONNECT: zookeeper1, zookeeper2, zookeeper3
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9094
        depends_on:
            - zookeeper1
            - zookeeper2
            - zookeeper3
